/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sebco
 */
public class Consultas_Doc extends javax.swing.JFrame {

    /**
     * Creates new form Consultas_Doc
     */
    public Consultas_Doc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RADIOPACIENTE = new javax.swing.JRadioButton();
        CITASRADIO = new javax.swing.JRadioButton();
        RADIODIAG = new javax.swing.JRadioButton();
        RADIOHOSP = new javax.swing.JRadioButton();
        CBDiagnosticos = new javax.swing.JComboBox<>();
        CBCitas = new javax.swing.JComboBox<>();
        CBPaciente = new javax.swing.JComboBox<>();
        CBTratamientos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        DocTable = new javax.swing.JTable();
        RADIOTRATA = new javax.swing.JRadioButton();
        CBHospitalizacion = new javax.swing.JComboBox<>();
        btnSHOW = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        btnHTML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RADIOPACIENTE.setText("Paciente ");

        CITASRADIO.setText("Citas");

        RADIODIAG.setText("Diagnosticos ");

        RADIOHOSP.setText("Hospitalización");

        CBDiagnosticos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad según Nivel", "Cantidad según Paciente" }));

        CBCitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad según Especialidad", "Cantidad según Rango de Fechas", "Cantidad según Estado" }));

        CBPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnostico según Nivel", "Diagnostico según Rango de Fechas", "Diagnostico según Nombre", "Tratamiento según Nombre", "Tratamiento según Tipo", "Tratamiento según Rango de Fechas" }));

        CBTratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Según Tipo", "Conteo General", "Según Especialidad", "Según Paciente" }));

        DocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DocTable);

        RADIOTRATA.setText("Tratamientos");

        CBHospitalizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Detalle General de Paciente" }));

        btnSHOW.setText("SHOW");

        btnCSV.setText("CSV");

        jLabel1.setText("Reportes");

        btnPDF.setText("PDF");

        btnHTML.setText("HTML");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RADIOPACIENTE)
                                    .addComponent(CBDiagnosticos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CITASRADIO)
                                        .addGap(163, 163, 163)
                                        .addComponent(RADIOHOSP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSHOW))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CBTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(334, 334, 334)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCSV)
                                            .addComponent(btnPDF)
                                            .addComponent(btnHTML))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CBCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CBHospitalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(20, 20, 20))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RADIODIAG)
                                .addGap(139, 139, 139)
                                .addComponent(RADIOTRATA)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RADIOPACIENTE)
                    .addComponent(CITASRADIO)
                    .addComponent(RADIOHOSP)
                    .addComponent(btnSHOW))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHospitalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RADIODIAG)
                            .addComponent(RADIOTRATA))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBDiagnosticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHTML)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas_Doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas_Doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas_Doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas_Doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas_Doc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CBCitas;
    public javax.swing.JComboBox<String> CBDiagnosticos;
    public javax.swing.JComboBox<String> CBHospitalizacion;
    public javax.swing.JComboBox<String> CBPaciente;
    public javax.swing.JComboBox<String> CBTratamientos;
    public javax.swing.JRadioButton CITASRADIO;
    public javax.swing.JTable DocTable;
    public javax.swing.JRadioButton RADIODIAG;
    public javax.swing.JRadioButton RADIOHOSP;
    public javax.swing.JRadioButton RADIOPACIENTE;
    public javax.swing.JRadioButton RADIOTRATA;
    public javax.swing.JButton btnCSV;
    public javax.swing.JButton btnHTML;
    public javax.swing.JButton btnPDF;
    public javax.swing.JButton btnSHOW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
